version: '3.8'
services:
  cloud9:
    image: sapk/cloud9:latest
    volumes:
      - /home/c9users/${NAMA_PELANGGAN}:/workspace
    restart: always
    ports:
      - "${PORT}:${PORT}"
    command:
      - --auth=${NAMA_PELANGGAN}:${PASSWORD_PELANGGAN}
      - --port=${PORT}
#Optinal uncomment if you need to use it.
#    mem_limit: ${MEMORY}
#    cpus: ${CPUS}
